version: '3.6'

services:
  players:
    container_name: gambot_players
    build:
      context: .
    volumes:
      - '.:/src'
    ports:
      - 5001:5000
    environment:
      - FLASK_APP=project/__init__.py
      - FLASK_ENV=development
      - APP_SETTINGS=project.config.DevelopmentConfig