version: '3.6'

services:
  base:
    container_name: gambot_players
    build:
      context: .
      dockerfile: Dockerfile-dev
    volumes:
      - '.:/src'
    ports:
      - 5001:5000
    environment:
      - FLASK_APP=project/__init__.py
      - FLASK_ENV=development
      - APP_SETTINGS=project.config.DevelopmentConfig
      - DATABASE_URL=postgres://postgres:postgres@db:5432/players_dev
      - DATABASE_TEST_URL=postgres://postgres:postgres@db:5432/players_test
    depends_on:
      - db
    networks:
      - gambotnetwork
    
  db:
    container_name: gambot_players_db
    build:
      context: ./project/db
      dockerfile: Dockerfile
    ports:
      - 5434:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - gambotnetwork

networks:
  gambotnetwork:
    driver: "bridge"
    name: gambotnetwork